// IntelliJ Grammar-Kit BNF for Johann
{
  tokens=[
    WHITE_SPACE='regexp:\s+'
    COMMENT='regexp:#.*'

    ID='regexp:[a-zA-Z][a-zA-Z0-9_]*'
    INT_DEC='regexp:-?[1-9][0-9_]*'
    INT_HEX='regexp:-?0x[0-9a-fA-F][0-9a-fA-F_]*'
    CHAR="regexp:'.'"
    STRING='regexp:"[^"]*"'
  ]
}

program ::= ( ( "pub" )? ( global_declaration | function_declaration ) )*
global_declaration ::= vardecl_
function_declaration ::= "fn" ID "(" parameter_list? ")" /*( "->" type )?*/ ( ";" | block )
private vardecl_ ::= type_and_name opt_assign
//                   | "let" name_and_type variable_initializer
//                   | "const" name_and_type variable_initializer
private type_and_name ::= type ( "*" )* ID
private opt_assign ::= ( "=" expr )? ";"
//name_and_type ::= ID ":" type
private parameter_list ::= type_opt_name ( "," type_opt_name )*
private type_opt_name ::= type ( "*" )* ( ID )?
private type ::= "bool"
               | "char"
               | "int"
               | "void"
//       | "(" type_list ")" "->" type
//type_list ::= type ( "," type )*
private block ::= "{" statement* "}"
statement ::= vardecl_
            | "if" expr block /*( "else" block )?*/
            | "while" expr block
            | "done" ";"
            | "again" ";"
            | "return" expr ";"
            | unary_expr "=" expr ";"
            | expr ";"
//            | block
            | ";"

/* Recursive descent is not ideal here, but it's straightforward to hand-code.
 * At the moment, matching the implementation is more useful than an efficient
 * (hypothetical) IDE.
 */
expr ::= cond_expr

private cond_expr ::= lor_expr // ( "?" expr ":" cond_expr )?

private lor_expr ::= land_expr // ( "||" land_expr )*

private land_expr ::= bor_expr // ( "&&" bor_expr )*

private bor_expr ::= bxor_expr // ( "^" bxor_expr )*

private bxor_expr ::= band_expr // ( "^" band_expr )*

private band_expr ::= eq_expr // ( "&" eq_expr )*

private eq_expr ::= rel_expr ( ( "=" | "!" /*| "==" | "!="*/ ) rel_expr )*

private rel_expr ::= shift_expr ( ( "<" | ">" /*| "<=" | ">="*/ ) shift_expr )*

private shift_expr ::= add_expr // ( ( "<<" | ">>" ) add_expr )*

private add_expr ::= mult_expr ( ( "+" | "-" ) mult_expr )*

private mult_expr ::= cast_expr ( ( "*" | "/" | "%" ) cast_expr )*

private cast_expr ::= unary_expr
//                    | "(" type ")" cast_expr

private unary_expr ::= postfix_expr
//                     | inc_op unary_expr
                     | un_op cast_expr
//                     | "sizeof" "(" type ")"
private un_op ::= "-" | "+" | "!" | "*" | "&"
//private inc_op ::= "++" | "--"

private postfix_expr ::= primary_expr (
                             "(" argument_list? ")"
//                             | "[" expr "]"
//                             | "." ID // todo: obj.method().another().field?
//                             | inc_op
                         )*
private argument_list ::= expr ( "," expr )*

private primary_expr ::= ID
                       | CHAR
                       | INT_DEC | INT_HEX | "0"
                       | STRING
                       | "true" | "false"
                       | "(" expr ")"
