site_name: Johann
copyright: Copyright &copy; 2025 <a href="https://github.com/barneyb">Barney Boisvert</a>
site_url: https://barneyb.github.io/johann
repo_url: https://github.com/barneyb/johann
repo_name: barneyb/johann
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - minify:
      minify_html: true
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
#    - navigation.sections
#    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
#    - toc.integrate
  icon:
    logo: material/music-rest-quarter
  favicon: images/rest.png
  palette:
    # Why primary/accept need to be declared thrice is completely unclear.
    - media: "(prefers-color-scheme)"
      primary: light green
      accent: light green
    - media: "(prefers-color-scheme: light)"
      primary: light green
      accent: light green
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: light green
      scheme: slate
extra_css:
  - stylesheets/theme-overrides.css
