site_name: Johann
copyright: Copyright &copy; 2025 Barney Boisvert
site_url: https://barneyb.github.io/johann
repo_url: https://github.com/barneyb/johann
repo_name: barneyb/johann
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
#    - navigation.sections
#    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
#    - toc.integrate
  icon:
    logo: material/music-rest-quarter
  favicon: images/rest.png
  palette:
    # Why primary/accept need to be declared thrice is completely unclear.
    - media: "(prefers-color-scheme)"
      primary: light green
      accent: light green
    - media: "(prefers-color-scheme: light)"
      primary: light green
      accent: light green
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: light green
      scheme: slate
extra_css:
  - stylesheets/extra.css
